#This is for SourceHut's build infrastructure
arch: null
environment: null
image: debian/testing
packages:
  - mtr-tiny
repositories: null
secrets: null
sources:
- https://github.com/baxterworks-build/ci-tests
tasks:
- run-tests: sudo bash ci-tests/test.sh
